### ISSUE TITLE
Wrong hour on maxpeaks

### ISSUE THREAD

**Issue by elden1337** [elden1337/peaqev-core#26]
States 1 as hour but should be 19

![image](https://user-images.githubusercontent.com/22585518/173684707-0e772044-d132-4603-9119-cc19f64272c0.jpeg)

![image](https://user-images.githubusercontent.com/22585518/173684719-e070d653-cf20-49dd-96df-2139ae658958.jpeg)

**Comment by elden1337** [comment]
@Brother-Blue didnt you push commits for this?

**Comment by Brother-Blue** [comment]
Not yet, I started looking into it but it got late. Will be working on it this weekend

**Comment by elden1337** [comment]
We ll have to think of a test case to convert back and forth between the tuple based obj and the dict necessary for export. 

The conversion methods are currently in different files (my bad)

**Comment by elden1337** [comment]
peaksmodel.py vs querytypes.py

I think they should obv be in the same class if possible.

**Comment by Brother-Blue** [comment]
I can update the PeaksModel class to have anything related to peaks and update things accordingly. Feels better to have those isolated from querytypes

**Comment by elden1337** [comment]
Agreed. If you find the time that sounds like a good path!
