### ISSUE TITLE
Asker Nett, Norway

### ISSUE THREAD

**Issue by kevinsch95** [elden1337/peaqev-core#57]
I couldn't find Asker Nett in the list. I chose "Elvia" in my HA installation in the meantime. It's essentially the same. 

https://askernett.no/ny-nettleiemodell-for-alle-fra-1-juli-2022/

I already created a pull request, and I think I've done it correctly. Not sure if I also have to create this issue, as this is my first commit ever to a project on GitHub. Opened this for an easier overview? 

#56

**Comment by elden1337** [comment]
Hi. Thanks for contributing! 
It's fine, i get the pr as an issue itself (but somehow i didnt get a notification).
